ROMAN_TO_ENG = {
    "qr code dikhao": "show my qr code",
    "qr dikhao": "show my qr code",
    "mera qr kahan hai": "where is my qr code",
    "qr kahan hai": "where is my qr code",
    "qr code kahan hai": "where is my qr code",
    "apna qr code dekhao": "show my qr code",
    "barcode dikhao": "show my barcode",
    "balance check karo": "check my balance",
    "balance dekhna hai": "check my balance",
    "paise dekhna hai": "check my balance",
    "mere paise kitne hain": "check my balance",
    "kitne paise hain": "check my balance",
    "muje balance dikhado": "check my balance",
    "light on karo": "turn on the flashlight",
    "location dikhao": "show my current location",
    "setting kholo": "open the app settings",
    "app ki settings kholo": "open the app settings",
    "mje transaction dikha do": "show my transactions",
    "transactions dikhao": "show my transactions",
    "meri transactions": "show my transactions",
    "transaction history dikhado": "show my transactions",
    "mje qr dikhao mera": "show my qr code",
    "kl qr bnaya ta uski transaction": "show transactions for qr code",
    "yesterday qr ki transaction": "show transactions for qr code",
    "qr se ki gayi transactions dikhado": "show transactions for qr code",
    "meri payments": "show my payments",
    "payment dikhado": "show my payments",
    "recent payments": "show my payments",
    "mje paise dekhne hain": "check my balance",
    "mje x se paise lene hain": "i want to request money from someone",
    "ali se paise mangwani hain": "i want to request money from someone",
    "request money from ali": "i want to request money from someone",
    "mje logout krna hai": "log me out",
    "logout krdo": "log me out",
    "sign out karo": "log me out",
    "mje login krna hai": "log me in",
    "login krdo": "log me in",
    "log in karwana hai": "log me in",
    "mje login krna haii, mera number x hai": "log me in",
    "sign up kese krenge?": "how to sign up",
    "sign up krna hai": "how to sign up",
    "mje account banana hai": "how to sign up",
    "register kaise karna hai": "how to sign up"
}

def translate_to_english(text):
    return ROMAN_TO_ENG.get(text.strip().lower(), text)

